export const cardData = [
    {
        image: "src/assets/stock/dbms1.png",
        title: "DBMS Detailed Complete Notes",
        author: "Mo Khairy",
        pages: "28 Pages",
        likes: 30,
        comments: 10,
        downloads: 200,
        views: 6,
    },
    {
        image: "./src/assets/stock/dbms1.png",
        title: "Computer Networks Notes",
        author: "John Doe",
        pages: "45 Pages",
        likes: 50,
        comments: 15,
        downloads: 350,
        views: 12,
    },
    {
        image: "./src/assets/stock/dbms1.png",
        title: "Computer Networks Notes",
        author: "John Doe",
        pages: "45 Pages",
        likes: 50,
        comments: 15,
        downloads: 350,
        views: 12,
    },
    {
        image: "./src/assets/stock/dbms1.png",
        title: "Computer Networks Notes",
        author: "John Doe",
        pages: "45 Pages",
        likes: 50,
        comments: 15,
        downloads: 350,
        views: 12,
    },
    {
        image: "./src/assets/stock/dbms1.png",
        title: "Computer Networks Notes",
        author: "John Doe",
        pages: "45 Pages",
        likes: 50,
        comments: 15,
        downloads: 350,
        views: 12,
    },
    {
        image: "./src/assets/stock/dbms1.png",
        title: "Computer Networks Notes",
        author: "John Doe",
        pages: "45 Pages",
        likes: 50,
        comments: 15,
        downloads: 350,
        views: 12,
    },
    {
        image: "./src/assets/stock/dbms1.png",
        title: "Computer Networks Notes",
        author: "John Doe",
        pages: "45 Pages",
        likes: 50,
        comments: 15,
        downloads: 350,
        views: 12,
    },
];
